services:
    project_app.admin.cocktail_admin:
        class: Project\AppBundle\Admin\CocktailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "project_app.admin.cocktails" }
        arguments:
            - ~
            - Project\AppBundle\Entity\Cocktail
            - SonataAdminBundle:CRUD

    project_app.admin.cocktail_component_admin:
          class: Project\AppBundle\Admin\CocktailComponentAdmin
          tags:
              - { name: sonata.admin, manager_type: orm }
          arguments:
              - ~
              - Project\AppBundle\Entity\CocktailComponent
              - SonataAdminBundle:CRUD

    project_app.admin.ingredient_admin:
        class: Project\AppBundle\Admin\IngredientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "project_app.admin.ingredients" }
        arguments:
            - ~
            - Project\AppBundle\Entity\Ingredient
            - SonataAdminBundle:CRUD