imports:
    - { resource: admin.yml }

services:
    project_app.service.cocktail_finder:
        class: Project\AppBundle\Service\CocktailFinderService
        calls:
            - [setDoctrine, ["@doctrine"]]