db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
php:
    build: php-fpm
    volumes:
        - ./../../project:/var/www/ProjectDemo
    ports:
        - 9000:9000
    tty: true
    links:
        - db
nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes:
        - ./logs/nginx/:/var/log/nginx
