doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                server_version: 5.5
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        proxy_namespace: Proxies
        proxy_dir: "%kernel.cache_dir%/doctrine/orm/Proxies"
        default_entity_manager: default
        metadata_cache_driver: array
        query_cache_driver:
            type: service
            id: "doctrine_cache.providers.file_system"
        result_cache_driver:
            type: service
            id: "doctrine_cache.providers.file_system"
        resolve_target_entities:
        second_level_cache:
            region_cache_driver:
                type: service
                id: "doctrine_cache.providers.file_system"
            regions:
                concurrent_entity_region:
                    type: filelock
                    cache_driver:
                        type: service
                        id: "doctrine_cache.providers.file_system"
                entity_region:
                     lifetime: 0
                     cache_driver:
                        type: service
                        id: "doctrine_cache.providers.file_system"
            log_enabled: "%kernel.debug%"

doctrine_cache:
    providers:
        file_system: {type: file_system}