project_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

project_base:
    resource: "@ProjectAppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin