imports:
    - { resource: ../_base/config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/dev/routing.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            buffer_size: 100
        console:
            type:   console
            bubble: false

swiftmailer:
    spool:
        type: file
        path: "%kernel.cache_dir%/swiftmailer/spool"